/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as IndexImport } from './routes/index'
import { Route as LayoutTradingImport } from './routes/_layout/trading'
import { Route as LayoutNotesImport } from './routes/_layout/notes'
import { Route as LayoutKanbanImport } from './routes/_layout/kanban'
import { Route as LayoutGymImport } from './routes/_layout/gym'
import { Route as LayoutFootballImport } from './routes/_layout/football'
import { Route as LayoutFinanceImport } from './routes/_layout/finance'
import { Route as LayoutCodeImport } from './routes/_layout/code'
import { Route as LayoutGymProgramsImport } from './routes/_layout/gym.programs'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutTradingRoute = LayoutTradingImport.update({
  id: '/trading',
  path: '/trading',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutNotesRoute = LayoutNotesImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutKanbanRoute = LayoutKanbanImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutGymRoute = LayoutGymImport.update({
  id: '/gym',
  path: '/gym',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutFootballRoute = LayoutFootballImport.update({
  id: '/football',
  path: '/football',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutFinanceRoute = LayoutFinanceImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCodeRoute = LayoutCodeImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutGymProgramsRoute = LayoutGymProgramsImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => LayoutGymRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/code': {
      id: '/_layout/code'
      path: '/code'
      fullPath: '/code'
      preLoaderRoute: typeof LayoutCodeImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/finance': {
      id: '/_layout/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof LayoutFinanceImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/football': {
      id: '/_layout/football'
      path: '/football'
      fullPath: '/football'
      preLoaderRoute: typeof LayoutFootballImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/gym': {
      id: '/_layout/gym'
      path: '/gym'
      fullPath: '/gym'
      preLoaderRoute: typeof LayoutGymImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/kanban': {
      id: '/_layout/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof LayoutKanbanImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/notes': {
      id: '/_layout/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof LayoutNotesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/trading': {
      id: '/_layout/trading'
      path: '/trading'
      fullPath: '/trading'
      preLoaderRoute: typeof LayoutTradingImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/gym/programs': {
      id: '/_layout/gym/programs'
      path: '/programs'
      fullPath: '/gym/programs'
      preLoaderRoute: typeof LayoutGymProgramsImport
      parentRoute: typeof LayoutGymImport
    }
  }
}

// Create and export the route tree

interface LayoutGymRouteChildren {
  LayoutGymProgramsRoute: typeof LayoutGymProgramsRoute
}

const LayoutGymRouteChildren: LayoutGymRouteChildren = {
  LayoutGymProgramsRoute: LayoutGymProgramsRoute,
}

const LayoutGymRouteWithChildren = LayoutGymRoute._addFileChildren(
  LayoutGymRouteChildren,
)

interface LayoutRouteChildren {
  LayoutCodeRoute: typeof LayoutCodeRoute
  LayoutFinanceRoute: typeof LayoutFinanceRoute
  LayoutFootballRoute: typeof LayoutFootballRoute
  LayoutGymRoute: typeof LayoutGymRouteWithChildren
  LayoutKanbanRoute: typeof LayoutKanbanRoute
  LayoutNotesRoute: typeof LayoutNotesRoute
  LayoutTradingRoute: typeof LayoutTradingRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutCodeRoute: LayoutCodeRoute,
  LayoutFinanceRoute: LayoutFinanceRoute,
  LayoutFootballRoute: LayoutFootballRoute,
  LayoutGymRoute: LayoutGymRouteWithChildren,
  LayoutKanbanRoute: LayoutKanbanRoute,
  LayoutNotesRoute: LayoutNotesRoute,
  LayoutTradingRoute: LayoutTradingRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof LayoutRouteWithChildren
  '/code': typeof LayoutCodeRoute
  '/finance': typeof LayoutFinanceRoute
  '/football': typeof LayoutFootballRoute
  '/gym': typeof LayoutGymRouteWithChildren
  '/kanban': typeof LayoutKanbanRoute
  '/notes': typeof LayoutNotesRoute
  '/trading': typeof LayoutTradingRoute
  '/gym/programs': typeof LayoutGymProgramsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof LayoutRouteWithChildren
  '/code': typeof LayoutCodeRoute
  '/finance': typeof LayoutFinanceRoute
  '/football': typeof LayoutFootballRoute
  '/gym': typeof LayoutGymRouteWithChildren
  '/kanban': typeof LayoutKanbanRoute
  '/notes': typeof LayoutNotesRoute
  '/trading': typeof LayoutTradingRoute
  '/gym/programs': typeof LayoutGymProgramsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/code': typeof LayoutCodeRoute
  '/_layout/finance': typeof LayoutFinanceRoute
  '/_layout/football': typeof LayoutFootballRoute
  '/_layout/gym': typeof LayoutGymRouteWithChildren
  '/_layout/kanban': typeof LayoutKanbanRoute
  '/_layout/notes': typeof LayoutNotesRoute
  '/_layout/trading': typeof LayoutTradingRoute
  '/_layout/gym/programs': typeof LayoutGymProgramsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/code'
    | '/finance'
    | '/football'
    | '/gym'
    | '/kanban'
    | '/notes'
    | '/trading'
    | '/gym/programs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/code'
    | '/finance'
    | '/football'
    | '/gym'
    | '/kanban'
    | '/notes'
    | '/trading'
    | '/gym/programs'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/_layout/code'
    | '/_layout/finance'
    | '/_layout/football'
    | '/_layout/gym'
    | '/_layout/kanban'
    | '/_layout/notes'
    | '/_layout/trading'
    | '/_layout/gym/programs'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_layout"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/code",
        "/_layout/finance",
        "/_layout/football",
        "/_layout/gym",
        "/_layout/kanban",
        "/_layout/notes",
        "/_layout/trading"
      ]
    },
    "/_layout/code": {
      "filePath": "_layout/code.tsx",
      "parent": "/_layout"
    },
    "/_layout/finance": {
      "filePath": "_layout/finance.tsx",
      "parent": "/_layout"
    },
    "/_layout/football": {
      "filePath": "_layout/football.tsx",
      "parent": "/_layout"
    },
    "/_layout/gym": {
      "filePath": "_layout/gym.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/gym/programs"
      ]
    },
    "/_layout/kanban": {
      "filePath": "_layout/kanban.tsx",
      "parent": "/_layout"
    },
    "/_layout/notes": {
      "filePath": "_layout/notes.tsx",
      "parent": "/_layout"
    },
    "/_layout/trading": {
      "filePath": "_layout/trading.tsx",
      "parent": "/_layout"
    },
    "/_layout/gym/programs": {
      "filePath": "_layout/gym.programs.tsx",
      "parent": "/_layout/gym"
    }
  }
}
ROUTE_MANIFEST_END */
