/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SnippetsImport } from './routes/snippets'
import { Route as LayoutImport } from './routes/_layout'
import { Route as IndexImport } from './routes/index'
import { Route as DemoTanstackQueryImport } from './routes/demo.tanstack-query'
import { Route as LayoutGymImport } from './routes/_layout.gym'
import { Route as LayoutGymProgramsImport } from './routes/_layout.gym.programs'

// Create/Update Routes

const SnippetsRoute = SnippetsImport.update({
  id: '/snippets',
  path: '/snippets',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DemoTanstackQueryRoute = DemoTanstackQueryImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRoute,
} as any)

const LayoutGymRoute = LayoutGymImport.update({
  id: '/gym',
  path: '/gym',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutGymProgramsRoute = LayoutGymProgramsImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => LayoutGymRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/snippets': {
      id: '/snippets'
      path: '/snippets'
      fullPath: '/snippets'
      preLoaderRoute: typeof SnippetsImport
      parentRoute: typeof rootRoute
    }
    '/_layout/gym': {
      id: '/_layout/gym'
      path: '/gym'
      fullPath: '/gym'
      preLoaderRoute: typeof LayoutGymImport
      parentRoute: typeof LayoutImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryImport
      parentRoute: typeof rootRoute
    }
    '/_layout/gym/programs': {
      id: '/_layout/gym/programs'
      path: '/programs'
      fullPath: '/gym/programs'
      preLoaderRoute: typeof LayoutGymProgramsImport
      parentRoute: typeof LayoutGymImport
    }
  }
}

// Create and export the route tree

interface LayoutGymRouteChildren {
  LayoutGymProgramsRoute: typeof LayoutGymProgramsRoute
}

const LayoutGymRouteChildren: LayoutGymRouteChildren = {
  LayoutGymProgramsRoute: LayoutGymProgramsRoute,
}

const LayoutGymRouteWithChildren = LayoutGymRoute._addFileChildren(
  LayoutGymRouteChildren,
)

interface LayoutRouteChildren {
  LayoutGymRoute: typeof LayoutGymRouteWithChildren
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutGymRoute: LayoutGymRouteWithChildren,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof LayoutRouteWithChildren
  '/snippets': typeof SnippetsRoute
  '/gym': typeof LayoutGymRouteWithChildren
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/gym/programs': typeof LayoutGymProgramsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof LayoutRouteWithChildren
  '/snippets': typeof SnippetsRoute
  '/gym': typeof LayoutGymRouteWithChildren
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/gym/programs': typeof LayoutGymProgramsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/snippets': typeof SnippetsRoute
  '/_layout/gym': typeof LayoutGymRouteWithChildren
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/_layout/gym/programs': typeof LayoutGymProgramsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/snippets'
    | '/gym'
    | '/demo/tanstack-query'
    | '/gym/programs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/snippets' | '/gym' | '/demo/tanstack-query' | '/gym/programs'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/snippets'
    | '/_layout/gym'
    | '/demo/tanstack-query'
    | '/_layout/gym/programs'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  SnippetsRoute: typeof SnippetsRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  SnippetsRoute: SnippetsRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_layout",
        "/snippets",
        "/demo/tanstack-query"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/gym"
      ]
    },
    "/snippets": {
      "filePath": "snippets.tsx"
    },
    "/_layout/gym": {
      "filePath": "_layout.gym.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/gym/programs"
      ]
    },
    "/demo/tanstack-query": {
      "filePath": "demo.tanstack-query.tsx"
    },
    "/_layout/gym/programs": {
      "filePath": "_layout.gym.programs.tsx",
      "parent": "/_layout/gym"
    }
  }
}
ROUTE_MANIFEST_END */
